### ISSUE TITLE
SQL: Password Recovery Functionality

### ISSUE THREAD

**Issue by whojoey** [ViviTurtle/Speed-Rider#10]

**Comment by ViviTurtle** [comment]
Functionality as follows:

1) Insert Email into Textbox
~~2) Check if email exists~~
2) PHP: Send Password recovery email
~~3) Password reset~~

**Comment by ViviTurtle** [comment]
# Stored Procedures:

**SP_CHECK_EMAIL(<EMAIL>);**
@Checks if email is in DB
@Returns 1 if email found else returns 0 under the column: EMAIL_FOUND

Example:
Ex. Call SP_CHECK_EMAIL('vivi.langga@gmail.com');

---

**SP_PASSWORD_RESET(<PASS_HASH> ,<EMAIL>);**
@Updates password hash under corresponding email
@Doesnt return anything, Just updates password hash
@Should check by running: $result->rowCount(); 

Ex. Call SP_PASSWORD_RESET('test_pass','vivi.langga@gmail.com');

Example PHP:
$query->prepare('CALL SP_PASSWORD_RESET("test_pass","vivi.langga@gmail.com")');
$result -> $query>execute();
if  ($result->rowCount() > 0)
{
   //Results passed
}

**Comment by jamestousignant** [comment]
Professional program enables you reset administrator or user password for Microsoft SQL Server instantly regardless of the length, complexity, language and encoding of the password set before.

See full details at: http://www.mannatsoftware.com/stellar-phoenix-sql-password-recovery.html
